In [6]:
import numpy as np
def relu(x):
    return np.maximum(0, x)  
def relu_derivative(x):
    return (x > 0).astype(float)  
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)
def cross_entropy_loss(y_true, y_pred):
    m = y_true.shape[0]
    return -np.sum(y_true * np.log(y_pred + 1e-8)) / m  
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[1, 0, 0],  
              [0, 1, 0],  
              [0, 0, 1],  
              [0, 1, 0]])  
np.random.seed(0)
w1 = np.random.randn(2, 100) * 0.01   
b1 = np.zeros((1, 100))                
w2 = np.random.randn(100, 3) * 0.01  
b2 = np.zeros((1, 3))                
lr = 0.01
epochs = 10000
for epoch in range(epochs):
    z1 = np.dot(X, w1) + b1
    a1 = relu(z1)
    z2 = np.dot(a1, w2) + b2
    a2 = softmax(z2) 
    loss = cross_entropy_loss(y, a2)
    output_error = a2 - y 
    d2 = output_error  
    hidden_error = np.dot(d2, w2.T)  
    d1 = hidden_error * relu_derivative(a1)  
    w2 -= lr * np.dot(a1.T, d2)
    b2 -= lr * np.sum(d2, axis=0, keepdims=True)
    w1 -= lr * np.dot(X.T, d1)
    b1 -= lr * np.sum(d1, axis=0, keepdims=True)
print("\nPredictions after training:")
print(np.round(a2))  


Predictions after training:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
