In [2]:
import numpy as np

# Store binary patterns (-1 and 1)
patterns = np.array([
    [1, -1, 1, -1],
    [1, 1, -1, -1]
])

# Create weight matrix using Hebbian learning rule
W = sum(np.outer(p, p) for p in patterns)
np.fill_diagonal(W, 0)

# Test with noisy pattern
test_pattern = np.array([1, -1, -1, -1])

print("Stored Patterns:\n", patterns)
print("Weight Matrix:\n", W)
print("Initial Noisy Input:", test_pattern)

# Asynchronous recall function
def recall(x, W, steps=10):
    x = x.copy()
    for _ in range(steps):
        for i in range(len(x)):
            x[i] = 1 if np.dot(W[i], x) >= 0 else -1
    return x

# Predict
output = recall(test_pattern, W)
print("Recalled Pattern:", output)


Stored Patterns:
 [[ 1 -1  1 -1]
 [ 1  1 -1 -1]]
Weight Matrix:
 [[ 0  0  0 -2]
 [ 0  0 -2  0]
 [ 0 -2  0  0]
 [-2  0  0  0]]
Initial Noisy Input: [ 1 -1 -1 -1]
Recalled Pattern: [ 1  1 -1 -1]
